// Strict JSON parsing for LLM outputs that may include code fences
export function parseJsonStrict(text: string): Record<string, any> {
  const cleaned = (text || '')
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
  let obj: any;
  try {
    obj = JSON.parse(cleaned);
  } catch {
    obj = {
      meta: {},
      pagesUI: { pages: {} },
      explanation: 'Parse failure; fallback structure',
    };
  }
  if (!obj.meta) obj.meta = {};
  if (!obj.pagesUI) obj.pagesUI = { pages: {} };
  obj.meta = {
    ...(obj.meta || {}),
    optimizationExplanation: obj.meta?.optimizationExplanation || 'Generated by Gemini',
  };
  return obj;
}